/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue01.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue02.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue03.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue04.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue05.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue06.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue07.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue08.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue09.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue10.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue11.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue12-p1-40.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue12-p41-80.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue13.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue14.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue15.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue16.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue17.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue18.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue19.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue20.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue22.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue23.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue24.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue25.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue26.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue27.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue28.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue29.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue30.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue31.txt
/home/andrewdo/Media/projects/christmas/Christmas/ODochartaighNewslettersOCRed/issue32.txt
